version: "3.6"
services:
    mlflow:
        build: .
        container_name: mlflow
        ports:
            - 9000:9000
        command: mlflow server --host 0.0.0.0 --backend-store-uri /filestore --default-artifact-root s3://<BUCKET>/<FOLDER> --port 9000
        volumes:
            - ./filestore:/filestore
        environment:
            - AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID>
            - AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY>
            - AWS_REGION=us-west-2
