name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}        
    - name: Install PyTorch
      run: |
        python -m pip install --upgrade pip
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Install dependencies
      run: |        
        python setup.py sdist
        pip install dist/*
    - name: Test with pytest
      run: |
        sapsan test
